'use client';

import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import { Card } from '@/components/ui';
import { Tag, Hash } from 'lucide-react';
import { motion } from 'framer-motion';

export default function TagsPage() {
  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-12 h-12 bg-editorial-blue/20 rounded-sm flex items-center justify-center">
                <Tag className="w-6 h-6 text-editorial-blue" />
              </div>
              <div>
                <h1 className="font-crimson font-bold text-4xl text-ink">
                  Tags
                </h1>
                <p className="text-ink/60 font-dm">
                  Browse notes by topic and category
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Coming Soon Message */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <Card className="text-center py-12">
            <div className="w-16 h-16 bg-editorial-blue/20 rounded-full flex items-center justify-center mx-auto mb-4">
              <Hash className="w-8 h-8 text-editorial-blue" />
            </div>
            <h3 className="font-crimson font-bold text-2xl text-ink mb-2">
              Tag Browser Coming Soon
            </h3>
            <p className="text-ink/60 font-dm max-w-md mx-auto mb-4">
              This page will display all your tags and let you browse notes by topic.
              Tags are already being auto-generated by AI when you create notes.
            </p>
            <div className="flex flex-wrap gap-2 justify-center max-w-lg mx-auto">
              <span className="px-3 py-1 bg-highlight-amber/20 text-ink text-sm font-dm rounded-full">
                #politics
              </span>
              <span className="px-3 py-1 bg-editorial-blue/20 text-ink text-sm font-dm rounded-full">
                #technology
              </span>
              <span className="px-3 py-1 bg-editorial-green/20 text-ink text-sm font-dm rounded-full">
                #environment
              </span>
              <span className="px-3 py-1 bg-highlight-amber/20 text-ink text-sm font-dm rounded-full">
                #breaking-news
              </span>
            </div>
          </Card>
        </motion.div>
      </div>
    </DashboardLayout>
  );
}
